# Use nginx lightweight image
FROM nginx:alpine

# Remove default nginx html files
RUN rm -rf /usr/share/nginx/html/*

# Copy local project files into nginx's default web root
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80
